### ISSUE TITLE
Timeout while getting pending sender allocation ids

### ISSUE THREAD

**Issue by rotarur** [graphprotocol/indexer-rs#532]
**Describe the bug**
indexer-tap-agent is crashing because it's not able to get the pending sender allocations.

in upgrade indexer we have this amount of tap receipts:
```sql
indexer=> select count(*) from scalar_tap_receipts;

  count
----------
 35751122
(1 row)
```

this is the log I see in tap agent:

```json
  2024-12-06T13:14:13.268815Z  WARN sqlx::query: slow statement: execution time exceeded alert threshold, summary: "WITH grouped AS ( …", db.statement: "\n\
nWITH grouped AS (\n  SELECT\n    signer_address,\n    allocation_id\n  FROM\n    scalar_tap_receipts\n  GROUP BY\n    signer_address,\n    allocation_id\n)\n
SELECT\n  DISTINCT signer_address,\n  (\n    SELECT\n      ARRAY (\n        SELECT\n          DISTINCT allocation_id\n        FROM\n          grouped\n
 WHERE\n          signer_address = top.signer_address\n      )\n  ) AS allocation_ids\nFROM\n  grouped AS top\n", rows_affected: 0, rows_returned: 0, elapsed:
 29.992025861s, elapsed_secs: 29.992025861, slow_threshold: 1s
    at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.8.2/src/logger.rs:126
    in ractor::actor::Actor with id: "0.0"

thread 'main' panicked at crates/tap-agent/src/agent/sender_accounts_manager.rs:153:17:
Timeout while getting pending sender allocation ids
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /root/crates/tap-agent/src/agent.rs:151:10:
Failed to start sender accounts manager actor.: StartupFailed("Timeout while getting pending sender allocation ids")
```

The query failing was supposedly improved in this bug https://github.com/graphprotocol/indexer-rs/commit/bf662dc25e0d7c13709e897ec3484c34f0b26cfd#diff-ef687136cadbd96fab64700f3dff0e6a8378eb783a28c9b48d01de29b336f187R313

after I created the index I see it's being heavily used

```sql
indexer=> SELECT * FROM pg_stat_user_indexes WHERE indexrelname LIKE 'manual_scalar_tap_receipts_signer_address_allocation_id';
  relid   | indexrelid | schemaname |       relname       |                      indexrelname                       | idx_scan | idx_tup_read | idx_tup_fetch
----------+------------+------------+---------------------+---------------------------------------------------------+----------+--------------+---------------
 13223100 |   74117249 | public     | scalar_tap_receipts | manual_scalar_tap_receipts_signer_address_allocation_id |       14 |    175329410 |      31457862
(1 row)
```

the index created:
```sql
create index concurrently manual_scalar_tap_receipts_signer_address_allocation_id on scalar_tap_receipts (signer_address, allocation_id);
```

there might be another index missing

**Comment by rotarur** [comment]
the explain from for this query looks like this

```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Unique  (cost=1127936.63..1127947.75 rows=200 width=196) (actual time=87064.195..103454.142 rows=2 loops=1)
   CTE grouped
     ->  Group  (cost=1000.59..1078132.41 rows=1483 width=82) (actual time=13.499..8157.096 rows=8884 loops=1)
           Group Key: scalar_tap_receipts.signer_address, scalar_tap_receipts.allocation_id
           ->  Gather Merge  (cost=1000.59..1078117.58 rows=2966 width=82) (actual time=13.496..8150.992 rows=10909 loops=1)
                 Workers Planned: 2
                 Workers Launched: 2
                 ->  Group  (cost=0.56..1076775.20 rows=1483 width=82) (actual time=0.518..5735.907 rows=3636 loops=3)
                       Group Key: scalar_tap_receipts.signer_address, scalar_tap_receipts.allocation_id
                       ->  Parallel Index Only Scan using manual_scalar_tap_receipts_signer_address_allocation_id on scalar_tap_receipts  (cost=0.56..1001341.34 rows=15086772 width=82) (actual time=0.513..3943.161 rows=12068855 loops=3)
                             Heap Fetches: 6837538
   ->  Sort  (cost=49804.23..49807.93 rows=1483 width=196) (actual time=87064.191..100675.713 rows=8884 loops=1)
         Sort Key: top.signer_address, ((SubPlan 3))
         Sort Method: external merge  Disk: 3392664kB
         ->  CTE Scan on grouped top  (cost=0.00..49726.11 rows=1483 width=196) (actual time=8165.491..74732.708 rows=8884 loops=1)
               SubPlan 3
                 ->  Result  (cost=33.50..33.51 rows=1 width=32) (actual time=8.319..8.319 rows=1 loops=8884)
                       InitPlan 2 (returns $3)
                         ->  Unique  (cost=33.47..33.50 rows=7 width=164) (actual time=5.463..7.312 rows=8868 loops=8884)
                               ->  Sort  (cost=33.47..33.48 rows=7 width=164) (actual time=5.454..5.857 rows=8868 loops=8884)
                                     Sort Key: grouped.allocation_id
                                     Sort Method: quicksort  Memory: 1078kB
                                     ->  CTE Scan on grouped  (cost=0.00..33.37 rows=7 width=164) (actual time=0.004..2.433 rows=8868 loops=8884)
                                           Filter: (signer_address = top.signer_address)
                                           Rows Removed by Filter: 16
 Planning Time: 1.966 ms
 Execution Time: 104705.578 ms
(27 rows)
```
